version: "3.9"

services:
  api:
    container_name: api_entrega_s5
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=caio
      - DB_PASSWORD=1234
      - DB=users_database
      - SECRET_KEY=segredo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db_entrega_s5
    image: postgres:14.3-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=caio
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caio -d users_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_entrega_s5:/var/lib/postgresql/data

volumes:
  postgres_entrega_s5:
    driver: local
